import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/Header/Header';

const Home: NextPage = () => {
	return (
		<div className="bg-gray-100">
			<Head>
				<title>Market place</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
		</div>
	);
};

export default Home;
