import type { NextPage } from 'next';
import Head from 'next/head';
import { useGlobalContext } from '../context/Context';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	const { clients } = useGlobalContext();

	return (
		<div className={styles.container}>
			<Head>
				<title>Market place</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<p>{clients} </p>
		</div>
	);
};

export default Home;
